#!/bin/sh

# Example (run in root dir):
# ./terraform apply -var hostname=`hostname` tf

docker run --rm -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`:/root \
  -w /root \
  hashicorp/terraform:0.11.7 $@
